# Site settings
title: Forward, Code!
header-img: img/bluedoor.jpeg
email: cara.kane@gmail.com
copyright_name: carakane
description: > # this means to ignore newlines until "baseurl:"
  web << thoughts
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username:
github_username:  carakane
learn_profile: carakane
email_username: cara.kane@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5

paginate_path: /blog/page:num/

exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
